In [2]:
import numpy as np

a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 
print ('Applying amin() function:') 
print (np.amin(a)) 
print ('\n')  

Applying amin() function:
2




In [3]:
print ('Applying amax() function:') 
print (np.amax(a)) 
print ('\n')  

print ('Applying amax() function again:') 
print (np.amax(a, axis = 0))

Applying amax() function:
9


Applying amax() function again:
[8 7 9]


In [7]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 

print ('Our array is:') 
print (a) 
print ('\n')  

print ('Applying ptp() function:' )
print (np.ptp(a)) 
print ('\n' ) 

#print 'Applying ptp() function along axis 1:' 
print (np.ptp(a, axis = 1)) 
print ('\n')   

print( 'Applying ptp() function along axis 0:')
print (np.ptp(a, axis = 0)) 

Our array is:
[[3 7 5]
 [8 4 3]
 [2 4 9]]


Applying ptp() function:
7


[4 5 7]


Applying ptp() function along axis 0:
[6 3 6]


In [8]:
a = np.array([[30,65,70],[80,95,10],[50,90,60]])
np.median(a)

65.0

In [10]:
np.mean(a)

61.111111111111114

In [11]:
a.mean()

61.111111111111114

In [12]:
dir (np.linalg)

['LinAlgError',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_numpy_tester',
 '_umath_linalg',
 'absolute_import',
 'bench',
 'cholesky',
 'cond',
 'det',
 'division',
 'eig',
 'eigh',
 'eigvals',
 'eigvalsh',
 'info',
 'inv',
 'lapack_lite',
 'linalg',
 'lstsq',
 'matrix_power',
 'matrix_rank',
 'multi_dot',
 'norm',
 'pinv',
 'print_function',
 'qr',
 'slogdet',
 'solve',
 'svd',
 'tensorinv',
 'tensorsolve',
 'test']

In [13]:
# 3 * x[0] + x[1] = b[0] and x[0] + 2 * x1 = b[1]
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
x

array([2., 3.])